// SPDX-License-Identifier: Apache-2.0
//
// Copies the compiled proving material into `public/zk` so that Network mode's
// `FetchZkConfigProvider` can serve it. The keys are ~100 MB and are regenerated by
// `npm run compile`, so they are never committed and never part of a Sandbox build.
import { cp, mkdir, readdir, stat } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const source = join(here, '..', '..', 'contract', 'src', 'managed', 'stock-and-foil');
const target = join(here, '..', 'public', 'zk');

const exists = async (path) => {
  try {
    await stat(path);
    return true;
  } catch {
    return false;
  }
};

if (!(await exists(join(source, 'keys')))) {
  console.error(`No proving keys at ${join(source, 'keys')}. Run "npm run compile" first.`);
  process.exit(1);
}

await mkdir(target, { recursive: true });
for (const dir of ['keys', 'zkir']) {
  await cp(join(source, dir), join(target, dir), { recursive: true });
  const files = await readdir(join(target, dir));
  console.log(`staged ${files.length} files into public/zk/${dir}`);
}
console.log('Network mode can now serve the compiled verifier material from /zk.');
